spring:
  profiles:    active: dev
camel:  springboot:    shutdown-timeout: 2
  
---

spring:
  profiles: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.174.142:5432/dbUBS
    username: postgres
    password: lilian31
    
startRoute : timer:lerJson?period=10s
fromRoute : file:data/input?delete=true&readLock=none&moveFailed=error
toRoute1: file:data/output
message: DEV - Ambiente

  